data <- read.csv("Large.Calcium.csv", header = TRUE)
head(data)
str(data)
dim(Large.Calcium)
summary(data$Calcium)
sd(data$Calcium, na.rm = TRUE)
mean(data$Calcium, na.rm = TRUE)
quantile(data$Calcium, 0.25, na.rm = TRUE)
summary(data$Calcium[data$Sex == 1])
summary(data$Calcium[data$Sex == 2])
data$Sex <- factor(data$Sex,levels = c(1,2), labels = c("Male", "Female"))
sex.table <- table(data$Sex)
sex.table
barplot(table(data$Sex), main = "Bar Plot of Gender", ylab= "Count")
hist(data$Calcium, main = "Distribution of Calcium Levels", xlab = "Calcium (mmol/L)")
boxplot(data$Calcium, main = "Summary of Calcium Levels", ylab = "Calcium (mmol/L)")
boxplot(data$Calcium ~ data$Sex, main = "Summary of Calcium by Gender", ylab = "Calcium (mmol/L)")
str(data)
data$lab <- factor(data$lab, levels = c(1,2,3,4,5), labels =c("lab 1", "lab 2", "lab 3", "lab 4", "lab 5"))
lab.table <- table(data$lab)
lab.table
head(data)
str(data)
